/*
This class is responsible for keeping track of
student information including name, auto-generated ID,
classes enrolled, tuition balance
*/

import java.util.Scanner;

public class Student {
    private String name;
    private String gradeYear;
    private int gradeNum;
    private String studentID;
    private String courses="";
    private int tuitionBalance=0;
    private static int courseCost = 700;
    private static int id=1000;

    private static String[] subjects = {"Math", "English", "Computer Science",
            "Lab Science", "History"};
    private static String[] mathCourses = {"Algebra", "Discrete Mathematics",
            "Trigonometry", "Statistics", "Calculus"};
    private static String[] englishCourses = {"English Literature", "Creative Writing",
            "German Literature", "Old English", "Shakespeare"};
    private static String[] computerSciCourses = {"Programming", "Database Management",
            "Data Structures and Analysis", "Game Development",
            "Artificial Intelligence"};
    private static String[] labSciCourses = {"Ecology", "Genetics", "Cellular Biology",
            "Environmental Science", "Physics"};
    private static String[] historyCourses = {"American Government", "Epidemics",
            "World War II", "Medievel Europe", "Greek Mythology"};

    /*
    constructor
    Fees for every student is $700 per class enrolled
    Fees paid when student initialized is $0
    Student ID is a unique ID that is autogenerated
    Name of the Student
    Grade of the Student
    */
    public Student() {
        Scanner in = new Scanner(System.in);
        System.out.print("Enter Student Name: ");
        this.name = in.nextLine();

        System.out.print("\n\t1 - Freshman\n\t2 - Sophmore\n\t3 - Junior\n\t4 - Senior\n");
        int input = Util.inputPrompt("\nEnter student class level: ",
                "Invalid command.  Please enter a number between 1 and 4: ",
                1, 4);

        this.gradeNum = input;

        if (input == 1) {
            this.gradeYear = "Freshman";
        }
        else if (input == 2) {
            this.gradeYear = "Sophomore";
        }
        else if (input == 3) {
            this.gradeYear = "Junior";
        }
        else if (input == 4) {
            this.gradeYear = "Senior";
        }

        setStudentID();

    }

    //Set a unique Student ID
    private void setStudentID() {
        // Grade Level + ID
        id++;
        this.studentID =  gradeNum + "" + id;
    }

    /*Enroll student in courses
    Initialize to select a school subject and enroll in courses for selected subject
    Gives option for user to quit enrollment when finished
     */
    public void enroll() {
        while (true) {
            System.out.println("\nSCHOOL SUBJECTS");
            System.out.println("--------------------------");
            for (int x=0; x < subjects.length; x++) {
                System.out.println("\t" + (x + 1) + ". " + subjects[x]);
            }

            int subject = Util.inputPrompt("\nEnter subject to view courses (0 to finish enrolling): ",
                    "Invalid command. Please enter a number between 0 and " + (subjects.length) + ": ",
                    subjects.length);

            //List class options dependent on subject selected
            if (subject == 0) {
                break;
            }
            else if (subject == 1) {
                System.out.println("\nMATH COURSES");
                System.out.println("--------------------------");
                subjectEnroll(mathCourses);
            }
            else if (subject == 2) {
                System.out.println("\nENGLISH COURSES");
                System.out.println("--------------------------");
                subjectEnroll(englishCourses);
            }
            else if (subject == 3) {
                System.out.println("\nCOMPUTER SCIENCE COURSES");
                System.out.println("--------------------------");
                subjectEnroll(computerSciCourses);
            }
            else if (subject == 4) {
                System.out.println("\nLAB SCIENCE COURSES");
                System.out.println("--------------------------");
                subjectEnroll(labSciCourses);
            }
            else if (subject == 5) {
                System.out.println("\nHISTORY COURSES");
                System.out.println("--------------------------");
                subjectEnroll(historyCourses);
            }
        }
        System.out.println("\n" + name + " is enrolled in the below courses: " + courses);
    }

    //Enroll in courses for a selected subject
    private void subjectEnroll(String[] subjectCourses) {

        for (int x=0; x<subjectCourses.length; x++) {
            System.out.println("\t" + (x + 1) + ". " + subjectCourses[x]);
        }

        while (true) {
            int course = Util.inputPrompt("\nEnter course to enroll (0 to return to school subjects): ",
                    "Invalid command. Please enter a number between 0 and " + (subjectCourses.length) + ": ",
                    subjectCourses.length);
            if (course != 0) {
                courses = courses + "\n\t" + subjectCourses[course - 1];
                tuitionBalance = tuitionBalance + courseCost;
                System.out.println(name + " has been enrolled in " + subjectCourses[course - 1] + "!");
            }
            else {
                break;
            }
        }
    }

    //View current balance of student
    public void viewBalance() {
        System.out.println("\n" + name + "'s balance is: $" + tuitionBalance);
    }

    //Pay tuition and update school funds
    public void payTuition() {
        viewBalance();
        int payment = Util.inputPrompt("Enter their payment: $",
                "Invalid command. Please enter a valid dollar amount $");
        tuitionBalance = tuitionBalance - payment;
        viewBalance();
        School.updateTotalMoneyEarned(payment);
    }

    //METHOD OVERRIDE. Print all student information
    public String toString() {
        return "\nStudent Info" +
                "\n--------------------------" +
                "\nName: " + name +
                "\nGrade Level: " + gradeYear +
                "\nStudent ID: " + studentID +
                "\nCourses Enrolled" + courses +
                "\nBalance: $" + tuitionBalance +
                "\n--------------------------" +
                "\n";
    }

}
